### ISSUE TITLE
How to generate the signature of each point in a sliding-window manner?

### ISSUE THREAD

**Issue by dpengwen** [patrick-kidger/signatory#33]
Hi,
  I am very interested in the path signature. Your provided code is very helpful. However, when I run the signatory.signature(Path, depth), it only generates the signature of the whole path. If I want to generate the signature of each point in a sliding-window manner,  how should I change the code?

Thank you in advance.

**Comment by patrick-kidger** [comment]
For this your probably want `signatory.Path`. Have a look at the example -
https://signatory.readthedocs.io/en/latest/pages/examples/intervals.html

Does that help?

**Comment by dpengwen** [comment]
> For this your probably want `signatory.Path`. Have a look at the example -
> https://signatory.readthedocs.io/en/latest/pages/examples/intervals.html
> 
> Does that help?

**Comment by dpengwen** [comment]
It is very helpful. Whether could it work l like the convolution layer in deep learning?  I want to only specify the sliding-window size, and then generate the signature of each local position in parallel.

**Comment by dpengwen** [comment]
> For this your probably want `signatory.Path`. Have a look at the example -
> https://signatory.readthedocs.io/en/latest/pages/examples/intervals.html
> 
> Does that help?

It is very helpful. Whether could it work l like the convolution layer in deep learning?  I want to only specify the sliding-window size, and then generate the signature of each local position in parallel.

**Comment by patrick-kidger** [comment]
The other sensible thing you can do is to stack all of your windows into a batch dimension. You can get the windows themselves with `torch.Tensor.unfold`.
