### ISSUE TITLE
Error: unable to import signatory

### ISSUE THREAD

**Issue by Xylambda** [patrick-kidger/signatory#37]
Hi, after installing signatory with:
```python
pip install signatory==1.2.1.1.4.0
```

I get an importing error:
```python
$ python -c "import signatory"
Traceback (most recent call last):
  File "D:\Users\aperez\env\synthesizer\lib\site-packages\signatory\__init__.py", line 25, in <module>
    from . import impl
  File "D:\Users\aperez\env\synthesizer\lib\site-packages\signatory\impl.py", line 19, in <module>
    from . import _impl
ImportError: DLL load failed while importing _impl: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\aperez\env\synthesizer\lib\site-packages\signatory\__init__.py", line 28, in <module>
    raise ImportError('Caught ImportError:\n```\n{}\n```\nThis can probably be fixed by updating your version of '
ImportError: Caught ImportError:
```
DLL load failed while importing _impl: The specified procedure could not be found.
```
This can probably be fixed by updating your version of Python, e.g. from 3.6.6 to 3.6.9. See the FAQ in the documentation.
```

-----

I checked the [FAQ page](https://signatory.readthedocs.io/en/latest/pages/miscellaneous/faq.html#miscellaneous-faq-importing) and it says that the problem is caused by having an older Python version, but my version is 3.8.3, which is relatively new:

```python
$ python --version
Python 3.8.3
```

so I think the root of the problem may be another. I haven't seen any issue in this repo addressing this problem in Windows.

-----

### Environment details
```python
$ pip freeze
Bottleneck==1.3.2
certifi==2020.12.5
cycler==0.10.0
joblib==1.0.1
kiwisolver==1.3.1
llvmlite==0.36.0
matplotlib==3.4.0
mkl-fft==1.3.0
mkl-random==1.1.1
mkl-service==2.3.0
numba==0.53.1
numexpr==2.7.3
numpy @ file:///C:/ci/numpy_and_numpy_base_1603466732592/work
olefile==0.46
pandas==1.2.3
Pillow @ file:///C:/ci/pillow_1615224342392/work
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
scikit-learn==0.24.1
scipy==1.6.2
signatory==1.2.1.1.4.0
six @ file:///C:/ci/six_1605187374963/work
threadpoolctl==2.1.0
torch==1.8.1
torchaudio==0.8.1
torchvision==0.9.1
tqdm==4.59.0
typing-extensions @ file:///home/ktietz/src/ci_mi/typing_extensions_1612808209620/work
wincertstore==0.2
```

### MRE
```python
$ python -c "import signatory"
```

### System and machine info
Some data were removed

```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Skull
Registered Organization:   N/A
Original Install Date:     22/03/2021, 15:41:19
System Boot Time:          22/03/2021, 16:16:49
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 26 Stepping 5 GenuineIntel ~3201 Mhz
BIOS Version:              American Megatrends Inc. 0803   , 06/08/2012
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16.375 MB
Available Physical Memory: 10.339 MB
Virtual Memory: Max Size:  18.807 MB
Virtual Memory: Available: 10.660 MB
Virtual Memory: In Use:    8.147 MB
Page File Location(s):     C:\pagefile.sys
```

I've also tried remaking the environment and installing everything again, but the error persists.

Thanks in advance.

**Comment by patrick-kidger** [comment]
Thanks for the informative error report. (It's refreshing to be able to diagnose the issue immediately.)

So the issue is (or at least not helped by) installing an incompatible pair of versions of Signatory and PyTorch.

You've stated that you're installing Signatory version 1.2.1.1.4.0, which corresponds to version 1.2.1 of Signatory and version 1.4.0 of PyTorch. Meanwhile the version of PyTorch you have installed is 1.8.1.

The latest version of PyTorch currently supported by Signatory is 1.7.1. (Adding builds for 1.8.0, 1.8.1 would be easy, I just haven't done it yet.) So start off by installing PyTorch 1.7.1, and then installing Signatory via `pip install signatory==1.2.4.1.7.1 --no-cache-dir --force-reinstall`. The extra flags will help make sure you get the correct version of Signatory; `pip` sometimes uses caches things incorrectly because of the extra versioning complexity Signatory needs.

**Comment by Xylambda** [comment]
Hi,

Many thanks for the quick response! 

As you stated, that was, in fact, the root of the problem. After reinstalling both `torch` and `signatory`  with proper versions everything runs smoothly. 

I close the issue.

**Comment by Apple-PPon** [comment]
我的torch版本是1.8.1，signatory版本是1.2.6.1.7，为什么也是报错
