### ISSUE TITLE
ERROR: No matching distribution found for signatory==1.2.7.1.11.0

### ISSUE THREAD

**Issue by manuelarturosantana** [patrick-kidger/signatory#46]
Hello, 
I am trying to install the latest version of signatory (1.2.7) with pytorch 1.10.0 on windows. 
When I run the command from the readme
`pip install signatory==1.2.7.1.11.0 --no-cache-dir --force-reinstall`
I get the error 
`ERROR: Could not find a version that satisfies the requirement signatory==1.2.7.1.11.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4.1.2.0, 1.1.4.1.3.0, 1.1.5.1.2.0, 1.1.5.1.3.0, 1.1.6.1.2.0, 1.1.6.1.3.0, 1.1.6.1.3.1, 1.2.0.1.2.0, 1.2.0.1.3.0, 1.2.0.1.3.1, 1.2.0.1.4.0, 1.2.1.1.2.0, 1.2.1.1.3.0, 1.2.1.1.3.1, 1.2.1.1.4.0, 1.2.1.1.5.0, 1.2.2.1.2.0, 1.2.2.1.3.0, 1.2.2.1.3.1, 1.2.2.1.4.0, 1.2.2.1.5.0, 1.2.2.1.5.1, 1.2.3.1.2.0, 1.2.3.1.3.0, 1.2.3.1.3.1, 1.2.3.1.4.0, 1.2.3.1.5.0, 1.2.3.1.5.1, 1.2.3.1.6.0, 1.2.4.1.6.0, 1.2.4.1.7.0, 1.2.4.1.7.1, 1.2.6.1.6.0, 1.2.6.1.7.0, 1.2.6.1.7.1, 1.2.6.1.8.0, 1.2.6.1.8.1, 1.2.6.1.9.0)
ERROR: No matching distribution found for signatory==1.2.7.1.11.0
`
I am on windows using python 3.7.4. This seems strange to me seeing as this is exactly the command specified in the documentation. Any ideas?

**Comment by patrick-kidger** [comment]
Ah yeah, there was an issue somewhere in the build scripts, where everything built correctly but then failed to upload to PyPI. See the discussion in https://github.com/patrick-kidger/signatory/pull/45.

If you or anyone else figures out what's going on then I'd be happy to accept a PR fixing things. Going forward, updates like this are going to be largely reliant on community support, as I no longer plan to focus on this myself.
