### ISSUE TITLE
Is it possible to calculate new path points on signature?

### ISSUE THREAD

**Issue by mountain** [patrick-kidger/signatory#51]
Hi, folks,

I had checked the api docs at https://signatory.readthedocs.io/en/latest/pages/reference/libraryapi.html
and examples, but I failed to find one example or api call to get the new path points based on a learned signature.

I know signature is a representation of paths, i.e. we have transformations from paths to signatures.
Is it possible to predicate new path points based on a fixed learned signature?

Mingli

**Comment by patrick-kidger** [comment]
Is [signature inversion](https://signatory.readthedocs.io/en/latest/pages/reference/signatures-inversion.html) what you're after?

**Comment by mountain** [comment]
Thanks! It is!
