### ISSUE TITLE
Error running from python3.9.9 on a guix system

### ISSUE THREAD

**Issue by dcunited001** [patrick-kidger/signatory#58]
Can you advise me on these errors? Thank you

I believe I can run on a docker image on my other computer, which is an arch install where tensorflow/rocm can run. 

```python
import numpy as np
import torch as pt
import pandas as pdA

import signatory as sg
path = torch.rand(2,10,3)
```

I'm not sure whether I can run the same setup on this laptop.  It's also an AMD machine, but with integrated graphics and proprietery drivers. 

However, this error involves a `glibc` mismatch:

`libstdc++.so.6: version `GLIBCXX_3.4.29' not found`

I could run `patchelf` on some of the compiled artifacts downloaded/built via pip (these are not in the guix `/gnu/store` but are in the `.venv` folder). However, I can't easily run it on the guix `python3.9.9` package, since it's an immutable install.

Here's the results of `ldd /gnu/store/094bbaq6glba86h1d4cj16xhdi6fk2jl-gcc-10.3.0-lib/lib/libstdc++.so.6` 

```
        linux-vdso.so.1 (0x00007ffec66f4000)
        libm.so.6 => /home/dc/.guix-extra-profiles/devtools/devtools/lib/libm.so.6 (0x00007ff0d7f53000)
        libc.so.6 => /home/dc/.guix-extra-profiles/devtools/devtools/lib/libc.so.6 (0x00007ff0d7d91000)
        /gnu/store/ayc9r7162rphy4zjw8ch01pmyh214h82-glibc-2.33/lib/ld-linux-x86-64.so.2 (0x00007ff0d826b000)
        libgcc_s.so.1 => /gnu/store/094bbaq6glba86h1d4cj16xhdi6fk2jl-gcc-10.3.0-lib/lib/libgcc_s.so.1 (0x00007ff0d7d77000)
```

And the error (with `readelf` on `libstdc++` here: https://0x0.st/HKSv.txt)

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 import signatory as sg
      2 path = torch.rand(2,10,3)

File ~/src/pytest/.direnv/python-3.9.9/lib/python3.9/site-packages/signatory/__init__.py:25
     22 import torch  # must be imported before anything from signatory
     24 try:
---> 25     from . import impl
     26 except ImportError as e:
     27     if 'specified procedure could not be found' in str(e):

File ~/src/pytest/.direnv/python-3.9.9/lib/python3.9/site-packages/signatory/impl.py:19
     15 """Provides an interface to _impl."""
     18 # noinspection PyUnresolvedReferences
---> 19 from . import _impl
     22 # For some reason some exceptions on a Mac are converted to RuntimeErrors rather than ValueErrors.
     23 # So we have to make a conversion.
     24 # This isn't perfect; any genuine RuntimeErrors will now always be ValueErrors.
     25 # So for consistency across platforms we _always_ convert RuntimeErrors to ValueErrors.
     26 def _wrap(fn):
     27     # We'd like to perform a check that fn is actually a function here
     28     # But that throws an error with the mocking used in the documentation
   (...)
     32     # but again it fails with autodoc.
     33     # Not super important, as nothing in this module should be public anyway.

ImportError: /gnu/store/094bbaq6glba86h1d4cj16xhdi6fk2jl-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/dc/src/pytest/.direnv/python-3.9.9/lib/python3.9/site-packages/signatory/_impl.cpython-39-x86_64-linux-gnu.so)
```

**Comment by dcunited001** [comment]
Also, these notes describe [my level of knowledge regarding path signatures](https://github.com/dcunited001/zettelkasten/blob/master/slips/20230424063753-math_path_signature_applied_for_great_machine_learns.org). It's not much, but I've been studying to apply it to a Kaggle competition on ASL. 

It's probably too late to do much (and it seems it won't work with the TFLite requirements, as they basically exclude GRU/LSTM), but I am interested in applying what I've learned so far to time series analysis on the supplied Mediapipe landmarks.

**Comment by patrick-kidger** [comment]
Anything beyond [this link](https://signatory.readthedocs.io/en/latest/pages/miscellaneous/faq.html#problems-with-importing-or-installing-signatory) isn't something I can really help with.

Realistically I'm afraid Signatory isn't really maintained any more!

**Comment by dcunited001** [comment]
well I thought I'd ask. I can run with GPU on another system, but some of the papers imply the compute can be expensive without OpenCL.

Thanks anyways. I'm looking forward to trying out the library.

**Comment by dcunited001** [comment]
also @patrick-kidger i had a idea to use path signatures in a method for mesh manifold validation. 

it requires some assumptions about the health of the mesh/manifold and would be difficult to use when the mesh legitimately have holes. 

basically, you run a particle shader with force splatting based on the triangle normals (and vectors in the opposite direction.) while the shader runs and the particles are directed torwards the mesh, which depending on the convexity of various regions will direct them through any holes. as the shader runs, you collect the particle positions into a memory buffer. afterwards, the path signature can identify hotspots where too many particle paths passed through what you assume to be a surface. this is done either visually with a heatmap or in an automated manner.

A variant of this path-signature process may be generally applicable to higher-dimensional manifolds, which would probably be more useful in a pure maths situation anyways.

there are probably better methods, but i've run into quite a few issues with importing meshes into blender or other software where the mesh can't be fixed. many of the surfaces in [Visualizing Mathematics with 3D Printing book](http://www.3dprintmath.com/) are difficult to fix, though the method doesn't suit those surfaces.

anyways, i thought it was a creative and visual use of the path signature methods.
